### ISSUE TITLE
Missing Dependency: publicsuffix

### ISSUE THREAD

**Issue by prologic** [seomoz/url-py#13]
```
XXXXXXXX@031986
Thu Feb 06 14:02:44
~
$ syspip install url
Downloading/unpacking url
  http://localhost:3141/root/pypi/+simple/url/ uses an insecure transport scheme (http). Consider using https if localhost:3141 has it available
  Using download cache from /Users/XXXXXXXX/.pip/cache/http%3A%2F%2Flocalhost%3A3141%2Froot%2Fpypi%2F%2Bf%2F3e1746ec712d371e0d35380647b33b93%2Furl-0.1.1.tar.gz
  Running setup.py (path:/Users/XXXXXXXX/build/url/setup.py) egg_info for package url

Installing collected packages: url
  Running setup.py install for url

Successfully installed url
Cleaning up...

XXXXXXXX@031986
Thu Feb 06 14:02:47
~
$ python
Python 2.7.6 (default, Nov 19 2013, 14:59:07)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from url import parse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XXXXXXXX/lib/python2.7/site-packages/url.py", line 36, in <module>
    from publicsuffix import PublicSuffixList
ImportError: No module named publicsuffix
>>>
```

**Comment by pombredanne** [comment]
Yes this has been fixed alright a while back and should be closed IMHO
